<template>
  <div class="invoice-wrapper">

    <form-wizard title="" subtitle="" class="invoice" color="#538C46">
      <tab-content title="Download Contract" icon="fa fa-cloud-download">
        <div class="invoice-box">
          <invoice-header :invoiceId="invoiceId" :date="date"></invoice-header>
          <download-contract :fileName="fileName" :fileUrl="fileUrl"></download-contract>
        </div>
      </tab-content>
      <tab-content title="Sign Contact" icon="fa fa-file-text-o" :before-change="processContract">
        <div class="invoice-box">
          <invoice-header :invoiceId="invoiceId" :date="date"></invoice-header>
          <sign-contract ref="signContract"></sign-contract>
        </div>
      </tab-content>
      <tab-content title="Pay Invoice" icon="fa fa-qrcode">
        <div class="invoice-box">
          <invoice-header :invoiceId="invoiceId" :date="date"></invoice-header>
          <pay-invoice :btcAmount="btcAmount" :bitcoinAddress="bitcoinAddress"></pay-invoice>
        </div>
      </tab-content>
    </form-wizard>
    <div>
      <div class="footer">This is a unique & encrypt invoice generated by CommerceBlock</div>
      <div class="footer-link">
        <a href="https://www.commerceblock.com/">https://www.commerceblock.com/</a>
      </div>
    </div>
  </div>
</template>

<script>
import gql from 'graphql-tag'
import HDPublicKey from 'bitcore-lib/lib/hdpublickey'
import InvoiceHeader from './InvoiceHeader.vue'
import DownloadContract from './steps/DownloadContract.vue'
import PayInvoice from './steps/PayInvoice.vue'
import SignContract from './steps/SignContract.vue'
import {
  FormWizard,
  TabContent
} from 'vue-form-wizard'
import {
  isEmpty,
  map
} from 'lodash'
import {
  computeFileHash,
  aggregateFileHashes,
  computeCommitmentAddress,
} from '../../lib/credentials'

export default {
  props: ['linkId'],
  components: {
    DownloadContract,
    PayInvoice,
    SignContract,
    InvoiceHeader,
    FormWizard,
    TabContent
  },
  data() {
    return {
      bitcoinAddress: null,
      errorResponse: null,
    }
  },
  computed: {
    invoiceId() {
      return this.invoiceSummary && this.invoiceSummary.invoiceId;
    },
    date() {
      return this.invoiceSummary && this.invoiceSummary.date;
    },
    btcAmount() {
      return this.invoiceSummary && this.invoiceSummary.btcAmount;
    },
    fileName() {
      return this.invoiceSummary && this.invoiceSummary.files[0].fileName;
    },
    fileUrl() {
      return this.invoiceSummary && this.invoiceSummary.files[0].fileUrl;
    },
    payeeCommitmentPK() {
      return this.invoiceSummary && this.invoiceSummary.payeeCommitmentPK;
    }
  },
  methods: {
    processContract() {
      console.log('we are here');

      if (!isEmpty(this.getContractFiles())) {
        this.bitcoinAddress = this.computeAddress();
        return true;
      } else {
        return 'error!';
      }
    },
    computeAddress() {
      const fileHashes = map(this.getContractFiles(), file => computeFileHash(file));
      const payerContractHash = aggregateFileHashes(fileHashes);
      const hdPublicKey = new HDPublicKey(this.payeeCommitmentPK);
      return computeCommitmentAddress(hdPublicKey, payerContractHash);
    },
    getContractFiles() {
      if (this.$refs && this.$refs.signContract) {
        return this.$refs.signContract.$refs.contractFiles.files;
      }
      return null;
    },
  },
  apollo: {
    invoiceSummary: {
      query: function () {
        return gql`query ListInvoiceSummary($linkId: ID!) {
          invoiceSummary(linkId: $linkId) {
              invoiceId
              linkId
              date
              btcAmount
              contractBasePK
              payeeCommitmentPK
              files {
                fileName
                fileUrl
              }
          }}`;
      },
      variables() {
        return {
          linkId: this.linkId,
        };
      },
      skip() {
        return isEmpty(this.linkId);
      },
      client: 'invoices'
    }
  }
}
</script>

<style scoped lang="scss">
.invoice-wrapper {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.invoice {
  width: 600px;
  margin: 5px;
}

.invoice-box {
  border-radius: 3px;
  background-color: #FFFFFF;
  box-shadow: 0 2px 7px 0 rgba(0, 0, 0, 0.25);
}

.footer {
  color: #141414;
  font-family: "Open Sans";
  font-size: 16px;
  line-height: 22px;
  text-align: center;
}

.footer-link {
  font-family: "Open Sans";
  font-size: 14px;
  line-height: 19px;
  text-align: center;

  a:link,
  a:visited,
  a:hover,
  a:active {
    color: rgba(20, 20, 20, 0.5);
  }
}
</style>
