<template>
  <div class="invoice-wrapper">

    <form-wizard title="" subtitle="" class="invoice" color="#538C46">
      <tab-content title="Download Contract" icon="fa fa-cloud-download">
        <div class="invoice-box">
          <invoice-header></invoice-header>
          <download-contract></download-contract>
        </div>
      </tab-content>
      <tab-content title="Sign Contact" icon="fa fa-file-text-o">
        <div class="invoice-box">
          <invoice-header></invoice-header>
          <sign-contact></sign-contact>
        </div>
      </tab-content>
      <tab-content title="Pay Invoice" icon="fa fa-qrcode">
        <div class="invoice-box">
          <invoice-header></invoice-header>
          <pay-invoice></pay-invoice>
        </div>
      </tab-content>
    </form-wizard>

    <div>
      <div class="footer">This is a unique & encrypt invoice generated by CommerceBlock</div>
      <div class="footer-link"><a href="https://commerceblock.com/">https://commerceblock.com/</a></div>
    </div>
  </div>
</template>

<script>
  import InvoiceHeader from './InvoiceHeader.vue'
  import DownloadContract from './steps/DownloadContract.vue'
  import PayInvoice from './steps/PayInvoice.vue'
  import SignContact from './steps/SignContact.vue'
  import {
    FormWizard,
    TabContent
  } from 'vue-form-wizard'
  import 'vue-form-wizard/dist/vue-form-wizard.min.css'

  export default {
    data: function () {
      return {

      }
    },
    components: {
      DownloadContract,
      PayInvoice,
      SignContact,
      InvoiceHeader,
      FormWizard,
      TabContent
    }
  }

</script>

<style scoped lang="scss">
  .invoice-wrapper {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  }

  .invoice {
    width: 600px;
    margin: 5px;
  }

  .invoice-box {
    border-radius: 3px;
    background-color: #FFFFFF;
    box-shadow: 0 2px 7px 0 rgba(0, 0, 0, 0.25);
  }

  .footer {
    color: #141414;
    font-family: "Open Sans";
    font-size: 16px;
    line-height: 22px;
    text-align: center;
  }

  .footer-link {
    font-family: "Open Sans";
    font-size: 14px;
    line-height: 19px;
    text-align: center;

    a:link, a:visited, a:hover, a:active {
      color: rgba(20, 20, 20, 0.5);
    }
  }

</style>
